depsets:
  - name: ray_base_test_depset
    operation: compile
    requirements:
      - requirements_test.txt
    constraints:
      - requirement_constraints_test.txt
    output: requirements_compiled.txt
    append_flags:
      - --no-annotate
      - --no-header
    override_flags:
      - --extra-index-url https://download.pytorch.org/whl/cu128

  - name: general_depset
    operation: compile
    requirements:
      - requirements_test.txt
    output: requirements_compiled_general.txt
    override_flags:
      - --extra
