depsets:
  - name: ray_base_test_depset
    requirements:
      - python/requirements.txt
      - python/requirements/cloud-requirements.txt
      - python/requirements/base-test-requirements.txt
    constraints:
      - python/requirements_compiled.txt
    output: python/test/requirements_compiled_ray_test_py311_cpu.txt
    operation: compile

  - name: general_depset
    operation: compile
    requirements:
      - python/requirements.txt
    output: python/test/requirements_compiled_general_py311_cpu.txt

  - name: cloud_depset
    operation: compile
    requirements:
      - python/requirements/cloud-requirements.txt
    output: python/test/requirements_compiled_cloud_req_py311_cpu.txt

  - name: base_test_depset
    operation: compile
    requirements:
      - python/requirements/base-test-requirements.txt
    output: python/test/requirements_compiled_base_test_py311_cpu.txt

  - name: llm_depset
    operation: compile
    requirements:
      - python/requirements/llm/llm-requirements.txt
    output: python/test/requirements_compiled_llm_py311_cpu.txt

  - name: llm_test_depset
    operation: compile
    requirements:
      - python/requirements/llm/llm-test-requirements.txt
    output: python/test/requirements_compiled_llm_test_py311_cpu.txt

  - name: compiled_ray_llm_test_depset
    operation: expand
    depsets:
      - general_depset
      - cloud_depset
      - base_test_depset
      - llm_depset
      - llm_test_depset
    constraints:
      - python/test/requirements_compiled_ray_test_py311_cpu.txt
    output: python/test/requirements_compiled_rayllm_test_py311_cpu.txt

  - name: compiled_ray_depset
    operation: subset
    source_depset: ray_base_test_depset
    requirements:
      - python/requirements.txt
    output: python/test/requirements_compiled_ray_py311_cpu.txt

  - name: compiled_ray_llm_depset
    operation: subset
    source_depset: compiled_ray_llm_test_depset
    requirements:
      - python/requirements.txt
      - python/requirements/llm/llm-requirements.txt
    output: python/test/requirements_compiled_rayllm_py311_cpu.txt
