depsets:
  - name: ray_base_test_depset
    requirements:
      - python/requirements.txt
      - python/requirements/cloud-requirements.txt
      - python/requirements/base-test-requirements.txt
    constraints:
      - /tmp/ray-deps/requirements_compiled.txt
    output: python/requirements_compiled_ray_test_${PYTHON_CODE}_${CUDA_CODE}.txt
    operation: compile
    override_flags:
      - --extra-index-url "https://download.pytorch.org/whl/${CUDA_CODE}"

  - name: general_depset
    operation: compile
    requirements:
      - python/requirements.txt
    output: python/requirements_compiled_general_${PYTHON_CODE}_${CUDA_CODE}.txt
    override_flags:
      - --extra-index-url "https://download.pytorch.org/whl/${CUDA_CODE}"

  - name: cloud_depset
    operation: compile
    requirements:
      - python/requirements/cloud-requirements.txt
    output: python/requirements_compiled_cloud_req_${PYTHON_CODE}_${CUDA_CODE}.txt
    override_flags:
      - --extra-index-url "https://download.pytorch.org/whl/${CUDA_CODE}"

  - name: base_test_depset
    operation: compile
    requirements:
      - python/requirements/base-test-requirements.txt
    output: python/requirements_compiled_base_test_${PYTHON_CODE}_${CUDA_CODE}.txt
    override_flags:
      - --extra-index-url "https://download.pytorch.org/whl/${CUDA_CODE}"

  - name: llm_depset
    operation: compile
    requirements:
      - python/requirements/llm/llm-requirements.txt
    output: python/requirements_compiled_llm_${PYTHON_CODE}_${CUDA_CODE}.txt
    override_flags:
      - --extra-index-url "https://download.pytorch.org/whl/${CUDA_CODE}"

  - name: llm_test_depset
    operation: compile
    requirements:
      - python/requirements/llm/llm-test-requirements.txt
    output: python/requirements_compiled_llm_test_${PYTHON_CODE}_${CUDA_CODE}.txt
    override_flags:
      - --extra-index-url "https://download.pytorch.org/whl/${CUDA_CODE}"

  - name: compiled_ray_llm_test_depset
    operation: expand
    depsets:
      - general_depset
      - cloud_depset
      - base_test_depset
      - llm_depset
      - llm_test_depset
    constraints:
      - python/requirements_compiled_ray_test_${PYTHON_CODE}_${CUDA_CODE}.txt
    output: python/requirements_compiled_rayllm_test_${PYTHON_CODE}_${CUDA_CODE}.txt
    override_flags:
      - --extra-index-url "https://download.pytorch.org/whl/${CUDA_CODE}"

  - name: compiled_ray_depset
    operation: subset
    source_depset: ray_base_test_depset
    requirements:
      - python/requirements.txt
    output: python/requirements_compiled_ray_${PYTHON_CODE}_${CUDA_CODE}.txt
    override_flags:
      - --extra-index-url "https://download.pytorch.org/whl/${CUDA_CODE}"

  - name: compiled_ray_llm_depset
    operation: subset
    source_depset: compiled_ray_llm_test_depset
    requirements:
      - python/requirements.txt
      - python/requirements/llm/llm-requirements.txt
    output: python/requirements_compiled_rayllm_${PYTHON_CODE}_${CUDA_CODE}.txt
    override_flags:
      - --extra-index-url "https://download.pytorch.org/whl/${CUDA_CODE}"
