group: macos tests
sort_key: "~macos"
steps:
  - label: ":ray: core: :mac: small & client tests"
    tags: 
      - core_cpp
      - python
      - macos_wheels
      - oss
    job_env: MACOS
    instance_type: macos
    soft_fail: true
    commands:
      - ./ci/ray_ci/macos/macos_ci.sh run_small_test

  - label: ":ray: core: :mac: medium a-j tests"
    tags: 
      - core_cpp
      - python
      - macos_wheels
      - oss
    job_env: MACOS
    instance_type: macos
    soft_fail: true
    commands:
      - ./ci/ray_ci/macos/macos_ci.sh run_medium_a_j_test

  - label: ":ray: core: :mac: medium k-z tests"
    tags: 
      - core_cpp
      - python
      - macos_wheels
      - oss
    job_env: MACOS
    instance_type: macos
    soft_fail: true
    commands:
      - ./ci/ray_ci/macos/macos_ci.sh run_medium_k_z_test

  - label: ":ray: core: :mac: large tests"
    tags: 
      - core_cpp
      - python
      - macos_wheels
      - oss
    job_env: MACOS
    instance_type: macos
    soft_fail: true
    parallelism: 3
    commands:
      - ./ci/ray_ci/macos/macos_ci.sh run_large_test

