group: rllib tests
steps:
  - label: ":brain: rllib: multi-gpu tests"
    tags: rllib
    instance_type: gpu-large
    commands:
      - bazel run //ci/ray_ci:test_in_docker -- //rllib/... rllib 
        --parallelism-per-worker 2
        --build-name rllibgpubuild
        --only-tags multi_gpu
    depends_on: rllibgpubuild
    job_env: forge

  - label: ":brain: rllib: flaky gpu tests"
    tags: rllib
    instance_type: gpu-large
    commands:
      - bazel run //ci/ray_ci:test_in_docker -- //rllib/... rllib 
        --run-flaky-tests
        --parallelism-per-worker 2
        --build-name rllibgpubuild
        --only-tags multi_gpu
    depends_on: rllibgpubuild
    job_env: forge

  # - label: ":brain: rllib: flaky tests"
  #   tags: rllib
  #   instance_type: large
  #   commands:
  #     # torch
  #     - bazel run //ci/ray_ci:test_in_docker -- //rllib/... rllib --run-flaky-tests --parallelism-per-worker 3
  #       --only-tags fake_gpus,learning_tests_discrete,learning_tests_with_ray_data,crashing_cartpole,stateless_cartpole,learning_tests_continuous
  #       --except-tags tf_only,tf2_only,multi_gpu
  #       --test-arg --framework=torch

  #     # tf2-static-graph
  #     - bazel run //ci/ray_ci:test_in_docker -- //rllib/... rllib --run-flaky-tests --parallelism-per-worker 3
  #       --only-tags tf_only
  #       --except-tags torch_only,tf2_only,no_tf_static_graph,multi_gpu
  #       --test-arg --framework=tf
  #       --skip-ray-installation # reuse the same docker image as the previous run

  #     # tf2-eager-tracing
  #     - bazel run //ci/ray_ci:test_in_docker -- //rllib/... rllib --run-flaky-tests --parallelism-per-worker 3
  #       --only-tags tf2_only
  #       --except-tags fake_gpus,torch_only,multi_gpu,no_tf_eager_tracing
  #       --test-arg --framework=tf2
  #       --skip-ray-installation # reuse the same docker image as the previous run

  #     # examples
  #     - bazel run //ci/ray_ci:test_in_docker -- //rllib/... rllib  --run-flaky-tests --parallelism-per-worker 3
  #       --only-tags examples
  #       --except-tags multi_gpu,gpu 
  #       --test-env RAY_USE_MULTIPROCESSING_CPU_COUNT=1
  #       --skip-ray-installation # reuse the same docker image as the previous run

  #     # rlmodule tests
  #     - bazel run //ci/ray_ci:test_in_docker -- //rllib/... rllib --run-flaky-tests --parallelism-per-worker 3
  #       --only-tags rlm
  #       --test-env RLLIB_ENABLE_RL_MODULE=1
  #       --test-env RAY_USE_MULTIPROCESSING_CPU_COUNT=1
  #       --skip-ray-installation # reuse the same docker image as the previous run
  #   depends_on: rllibbuild
  #   soft_fail: true
  #   job_env: forge
