group: Pre-release checks
depends_on:
  - forge
steps:
  - label: "Check Ray wheels"
    key: check-ray-wheels
    commands:
      - bazel run //ci/ray_ci/automation:check_ray_wheels_s3 -- --ray_version="${RAY_VERSION}" --commit_hash="${RAY_COMMIT}"
