group: Pre-release checks
steps:
  - label: "Check release blockers"
    depends_on: forge
    job_env: forge
    instance_type: small_branch
    commands:
      - bash .buildkite/release-automation/check_release_blockers.sh

  - trigger: "postmerge"
    label: "Trigger postmerge test"
      build:
        commit: "10009390b0ff61875b45cbab75052a89332b528e"
        branch: "master"
        message: "Triggered by release automation pipeline"