group: Pre-release checks
steps:
  - trigger: "postmerge"
    label: "Trigger postmerge test"
    build:
      commit: "$GREEN_COMMIT"
      branch: "$BRANCH"
      message: "Triggered by release automation pipeline"

# GREEN_COMMIT=10009390b0ff61875b45cbab75052a89332b528e
# BRANCH=master