group: Pre-release checks
steps:
  - label: "Check release blockers"
    key: check-release-blockers
    depends_on: forge
    job_env: forge
    instance_type: small_branch
    commands:
      - bash .buildkite/release-automation/check_release_blockers.sh

  - block: "Trigger tests & image builds"
    depends_on:
      - step: check-release-blockers
        allow_failure: true

  - label: "Trigger Postmerge test"
    trigger: "postmerge"
    if: build.env("COMMIT") != null && build.env("BRANCH") != null
    build:
      commit: "${COMMIT}"
      branch: "${BRANCH}"
      message: "Triggered by release-automation build #${BUILDKITE_BUILD_NUMBER}"
      env:
        NIGHTLY: 1
        RAYCI_CONTINUOUS_BUILD: 1
  
  - label: "Trigger Release nightly test"
    trigger: "release"
    if: build.env("COMMIT") != null && build.env("BRANCH") != null
    build:
      commit: "${COMMIT}"
      branch: "${BRANCH}"
      message: "Nightly test - triggered by release-automation build #${BUILDKITE_BUILD_NUMBER}"
      env:
        AUTOMATIC: 1
        RELEASE_FREQUENCY: "nightly"
  
  - wait

  - label: "Pre-release checks finished"
    key: pre-release-check-finished
    commands:
      - echo "Pre-release checks finished"


