group: Pre-release checks
steps:
  - label: "Check release blockers"
    depends_on: forge
    job_env: forge
    commands:
      - bash .buildkite/release-automation/check_release_blockers.sh

  - label: "Trigger postmerge test"
    trigger: "postmerge"
    build:
      commit: "${COMMIT}"
      branch: "${BRANCH}"
      message: "Triggered by release-automation build #${BUILDKITE_BUILD_NUMBER}"
  
  - label: "Trigger Release nightly test"
    trigger: "release"
    build:
      commit: "${COMMIT}"
      branch: "${BRANCH}"
      message: "Nightly test - triggered by release-automation build #${BUILDKITE_BUILD_NUMBER}"
      env:
        AUTOMATIC: 1
        RELEASE_FREQUENCY: "nightly"
  
  - label: "Trigger Release nightly-3x test"
    trigger: "release"
    build:
      commit: "${COMMIT}"
      branch: "${BRANCH}"
      message: "Nightly-3x test - triggered by release-automation build #${BUILDKITE_BUILD_NUMBER}"
      env:
        AUTOMATIC: 1
        RELEASE_FREQUENCY: "nightly-3x"
  
  - label: "Trigger Release weekly test"
    trigger: "release"
    build:
      commit: "${COMMIT}"
      branch: "${BRANCH}"
      message: "Weekly test - triggered by release-automation build #${BUILDKITE_BUILD_NUMBER}"
      env:
        AUTOMATIC: 1
        RELEASE_FREQUENCY: "weekly"
