group: Pre-release checks
steps:
  - trigger: "postmerge"
    label: "Trigger postmerge test"
    build:
      commit: build.env("COMMIT")
      branch: build.env("BRANCH")
      message: "Triggered by release automation pipeline {{build.env('BUILDKITE_BUILD_NUMBER')}}"
  
  - trigger: "release"
    label: "Trigger Release {{matrix}} test"
    matrix:
      - "nightly"
      - "nightly-3x"
      - "weekly"
    build:
      commit: build.env("COMMIT")
      branch: build.env("BRANCH")
      message: "Triggered by release automation pipeline {{build.env('BUILDKITE_BUILD_NUMBER')}}"
      env:
        AUTOMATIC=1
        RELEASE_FREQUENCY={{matrix}}
