group: Pre-release checks
steps:
  - trigger: "postmerge"
    label: "Trigger postmerge test"
      build:
        commit: "10009390b0ff61875b45cbab75052a89332b528e"
        branch: "master"
        message: "Triggered by release automation pipeline"