group: Pre-release checks
steps:
  - label: "Check release blockers"
    depends_on: forge
    job_env: forge
    instance_type: small_branch
    commands:
      - bash .buildkite/release-automation/check_release_blockers.sh
