group: Pre-release checks
steps:
  - label: "Check release blockers"
    key: check-release-blockers
    depends_on: forge
    job_env: forge
    instance_type: small_branch
    commands:
      - bash .buildkite/release-automation/check_release_blockers.sh

  - label: "Trigger Postmerge test"
    depends_on: check-release-blockers
    trigger: "postmerge"
    if: build.env("COMMIT") != null && build.env("BRANCH") != null
    build:
      commit: "${COMMIT}"
      branch: "${BRANCH}"
      message: "Triggered by release-automation build #${BUILDKITE_BUILD_NUMBER}"
  
  - label: "Trigger Release nightly test"
    depends_on: check-release-blockers
    trigger: "release"
    if: build.env("COMMIT") != null && build.env("BRANCH") != null
    build:
      commit: "${COMMIT}"
      branch: "${BRANCH}"
      message: "Nightly test - triggered by release-automation build #${BUILDKITE_BUILD_NUMBER}"
      env:
        AUTOMATIC: 1
        RELEASE_FREQUENCY: "nightly"
  
  - label: "Trigger Release nightly-3x test"
    depends_on: check-release-blockers
    trigger: "release"
    if: build.env("COMMIT") != null && build.env("BRANCH") != null
    build:
      commit: "${COMMIT}"
      branch: "${BRANCH}"
      message: "Nightly-3x test - triggered by release-automation build #${BUILDKITE_BUILD_NUMBER}"
      env:
        AUTOMATIC: 1
        RELEASE_FREQUENCY: "nightly-3x"
  
  - label: "Trigger Release weekly test"
    depends_on: check-release-blockers
    trigger: "release"
    if: build.env("COMMIT") != null && build.env("BRANCH") != null
    build:
      commit: "${COMMIT}"
      branch: "${BRANCH}"
      message: "Weekly test - triggered by release-automation build #${BUILDKITE_BUILD_NUMBER}"
      env:
        AUTOMATIC: 1
        RELEASE_FREQUENCY: "weekly"
