group: Upload & Validate wheels
steps:
  - block: "Upload wheels from S3 to TestPyPI"
    key: block-upload-wheels-testpypi
    depends_on:
      - forge

  - label: "Upload wheels from S3 to TestPyPI"
    key: upload-wheels-testpypi
    depends_on:
      - block-upload-wheels-testpypi
    job_env: forge
    instance_type: small_branch
    commands:
      - export RAY_VERSION="$RAY_VERSION"
      - export RAY_COMMIT="$RAY_COMMIT"
      - source .buildkite/release-automation/set-ray-version.sh
      - bazel run //ci/ray_ci/automation:upload_wheels_pypi --
        --ray_version="$$RAY_VERSION" --commit_hash="$$RAY_COMMIT"
        --pypi_env=test

  - block: "Download & validate Ray wheels from TestPyPI Windows"
    key: block-validate-windows-wheels
    depends_on: forge

  - label: "Windows x86_64"
    key: validate-windows-x86_64-wheels
    depends_on:
      - block-validate-windows-wheels
    job_env: WINDOWS
    instance_type: windows
    commands:
      - source .buildkite/release-automation/set-ray-version.sh
      - export RAY_HASH="$RAY_COMMIT"
      - ./release/util/sanity_check_windows.sh
