group: Validate wheels
steps:
  - name: forge
    wanda: .buildkite/release-automation/forge_x86_64.wanda.yaml

  - label: "check release blockers"
    depends_on: forge
    job_env: forge
    instance_type: small_branch
    commands:
      - bazel run //ci/ray_ci/automation:weekly_green_metric