group: Validate wheels
steps:
  - label: "Windows"
    job_env: WINDOWS
    instance_type: windows
    commands:
      - bash /c/workdir/ci/ray_ci/windows/install_tools.sh
      - bazel run //ci/ray_ci/release_automation:validate_windows_docker --
        --build-name windowsbuild
        --test-env=CI="1"
        --test-env=USERPROFILE
    depends_on: windowsbuild
