group: Upload & Validate wheels
steps:
  - name: windowsbuild
    wanda: ci/docker/windows.build.wanda.yaml
    instance_type: builder-windows

  - label: "Windows"
    job_env: WINDOWS
    instance_type: windows
    commands:
      - sleep 20m
