group: Validate wheels
steps:
  - name: forge
    wanda: .buildkite/release-automation/forge_x86_64.wanda.yaml

  - label: "Linux x86_64 Python {{matrix}}"
    depends_on: forge
    job_env: forge
    tags: disabled
    commands:
      - export PYTHON_VERSION={{matrix}}
      - export RAY_VERSION="$RAY_VERSION"
      - export RAY_HASH="$RAY_HASH"
      - bash -i .buildkite/release-automation/verify-linux-wheels.sh
    matrix:
      - "3.8"
      - "3.9"
      - "3.10"
      - "3.11"

  - name: forge_arm64
    wanda: .buildkite/release-automation/forge_arm64.wanda.yaml
    instance_type: builder-arm64

  - label: "Linux arm64 Python {{matrix}}"
    depends_on: forge_arm64
    instance_type: medium-arm64
    job_env: forge-arm64
    tags: disabled
    commands:
      - export PYTHON_VERSION={{matrix}}
      - export RAY_VERSION="$RAY_VERSION"
      - export RAY_HASH="$RAY_HASH"
      - bash -i .buildkite/release-automation/verify-linux-wheels.sh
    matrix:
      - "3.8"
      - "3.9"
      - "3.10"
      - "3.11"

  - label: "MacOS x86_64"
    job_env: MACOS
    instance_type: macos
    tags: disabled
    commands:
      - ./.buildkite/release-automation/verify-macos-wheels.sh x86_64

  - label: "MacOS arm64"
    job_env: MACOS
    instance_type: macos-arm64
    tags: disabled
    commands:
      - ./.buildkite/release-automation/verify-macos-wheels.sh arm64

  - label: "Windows"
    job_env: WINDOWS
    instance_type: windows
    commands:
      - bash -i /c/workdir/.buildkite/release-automation/verify-windows-wheels.sh
