group: Validate wheels
steps:
  - name: forge
    wanda: ci/docker/forge.wanda.yaml

  - label: "check release blockers"
    depends_on: forge
    job_env: forge
    instance_type: default
    commands:
      - bazel run //ci/ray_ci/automation:weekly_green_metric