group: Validate wheels
steps:
  - label: "Windows"
    job_env: WINDOWS
    instance_type: windows
    commands:
      - bash /c/workdir/ci/ray_ci/windows/install_tools.sh
      - source /c/workdir/release/util/pip_download_test.sh
