group: Validate wheels
steps:
  - name: windowsbuild
    wanda: ci/docker/windows.build.wanda.yaml
    instance_type: builder-windows

  - label: "Windows"
    job_env: WINDOWS
    instance_type: windows
    commands:
      - bash /c/workdir/ci/ray_ci/windows/install_tools.sh
      - bazel run //ci/ray_ci:test_in_docker -- //python/ray/train:test_windows ml
        --build-name windowsbuild
        --operating-system windows
        --test-env=CI="1"
        --test-env=RAY_CI_POST_WHEEL_TESTS="1"
        --test-env=USERPROFILE
      - bash /c/workdir/.buildkite/release-automation/verify-windows-wheels.sh
    depends_on: windowsbuild