group: Validate wheels
steps:
  - label: "Windows"
    depends_on: windowsbuild
    job_env: WINDOWS
    instance_type: windows
    commands:
      - bash /c/workdir/ci/ray_ci/windows/install_tools.sh
      - bash /c/workdir/.buildkite/release-automation/verify-windows-wheels.sh