group: Upload & Validate wheels
steps:
  - name: windowsbuild
    wanda: ci/docker/windows.build.wanda.yaml
    instance_type: builder-windows

  - label: "Windows"
    job_env: WINDOWS
    instance_type: windows
    commands:
      - docker run -it --rm --volume /tmp/artifacts:/artifact-mount --shm-size=2.5gb
        "$${RAYCI_WORK_REPO}":"$${RAYCI_BUILD_ID}"-windowsbuild /bin/bash -iecuo pipefail 
        "./.buildkite/release-automation/verify-windows-wheels.sh"
