group: Validate wheels
steps:
  - label: "Windows"
    job_env: WINDOWS
    instance_type: windows
    commands:
      - bazel run //ci/ray_ci:sanity_check -- --build-name windowsbuild --test-env=CI="1" --test-env=USERPROFILE