group: Validate wheels
steps:
  - name: forge
    wanda: .buildkite/release-automation/forge_x86_64.wanda.yaml

  - label: "Check release blockers count"
    depends_on: forge
    job_env: forge
    commands:
      bash .buildkite/release-automation/check-release-blockers.sh
  
  - label: "Trigger postmerge build"
    trigger: "postmerge"
    branches: "master"
    build:
      message: "Release automation trigger postmerge build"
      commit: build.env("COMMIT")
      branch: "master"
  
  - label: "Trigger release pipeline periodic test"
    trigger: "release"
    branches: "master"
    build:
      message: "Release automation trigger release pipeline periodic test"
      commit: build.env("COMMIT")
      branch: "master"
