group: Validate wheels
steps:
  - name: forge
    wanda: .buildkite/release-automation/forge_x86_64.wanda.yaml

  - label: "check release blockers"
    depends_on: forge
    job_env: forge
    commands:
      - bash -i .buildkite/release-automation/check_release_blockers.sh