base_image: {{ env["RAY_IMAGE_ML_NIGHTLY_GPU"] | default("anyscale/ray-ml:nightly-py37-gpu") }}

debian_packages:
  - curl

python:
  pip_packages:
    - ray-lightning
    - pytorch-lightning
    - lightning-bolts
    - tblib
    - torch==1.11.0
    - torchvision==0.12.0
  conda_packages: []

post_build_cmds:
  # Upgrade the Ray Lightning version, otherwise it will be cached in the Anyscale Docker image.
  - echo {{ env["TIMESTAMP"] }}
  - pip uninstall -y ray || true && pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
